# Generated by Django 3.2 on 2022-08-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20220717_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='adress_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='adress_line2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
