# Generated by Django 3.2 on 2022-08-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress_line1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adress_line2',
            new_name='address_line2',
        ),
    ]
